export const mockProducts = [
  {
    id: "1",
    name: "Nike Air Force 1 '07",
    category: "Men's Shoes",
    price: 8695,
    image: "/images/product-1.png",
    label: "Best Seller",
    colors: "2 Colours",
    gender: "men",
    size: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"],
    color: "White",
  },
  {
    id: "2",
    name: "Nike Dunk Low Retro",
    category: "Men's Shoes",
    price: 9695,
    image: "/images/product-2.png",
    label: "Best Seller",
    colors: "1 Colour",
    gender: "men",
    size: ["UK 7", "UK 8", "UK 9", "UK 11"],
    color: "Black",
  },
  {
    id: "3",
    name: "Nike Air Max 90",
    category: "Women's Shoes",
    price: 11895,
    image: "/images/product-3.png",
    label: "New",
    colors: "3 Colours",
    gender: "women",
    size: ["UK 4", "UK 5", "UK 6", "UK 7"],
    color: "Red",
  },
  {
    id: "4",
    name: "Nike Blazer Low '77 Jumbo",
    category: "Women's Shoes",
    price: 8595,
    image: "/images/product-4.png",
    label: "Sustainable Materials",
    colors: "1 Colour",
    gender: "women",
    size: ["UK 5", "UK 6", "UK 7", "UK 8"],
    color: "White",
  },
  {
    id: "5",
    name: "Air Jordan 1 Low",
    category: "Men's Shoes",
    price: 8995,
    image: "/images/product-5.png",
    label: "",
    colors: "1 Colour",
    gender: "men",
    size: ["UK 8", "UK 9", "UK 10", "UK 11"],
    color: "Blue",
  },
  {
    id: "6",
    name: "Nike Metcon 9",
    category: "Men's Training Shoes",
    price: 12795,
    image: "/images/product-6.png",
    label: "Just In",
    colors: "4 Colours",
    gender: "men",
    size: ["UK 7", "UK 8", "UK 9", "UK 10"],
    color: "Black",
  },
  {
    id: "7",
    name: "Nike Pegasus 40",
    category: "Women's Road Running Shoes",
    price: 11895,
    image: "/images/product-7.png",
    label: "",
    colors: "5 Colours",
    gender: "women",
    size: ["UK 4", "UK 5", "UK 6", "UK 7"],
    color: "Pink",
  },
  {
    id: "8",
    name: "Nike Air Force 1 Shadow",
    category: "Women's Shoes",
    price: 9295,
    image: "/images/product-8.png",
    label: "Best Seller",
    colors: "2 Colours",
    gender: "women",
    size: ["UK 5", "UK 6", "UK 7"],
    color: "Multi-Color",
  },
  {
    id: "9",
    name: "Nike Court Vision Low Next Nature",
    category: "Men's Shoes",
    price: 4995,
    image: "/images/product-9.png",
    label: "Sustainable Materials",
    colors: "1 Colour",
    gender: "men",
    size: ["UK 6", "UK 7", "UK 8", "UK 9"],
    color: "White",
  },
  {
    id: "10",
    name: "Nike Air Max SC",
    category: "Women's Shoes",
    price: 5995,
    image: "/images/product-10.png",
    label: "",
    colors: "2 Colours",
    gender: "women",
    size: ["UK 4", "UK 5", "UK 6"],
    color: "White",
  },
];
