export const mockProducts = [
  {
    id: "1",
    name: "Nike Air Force 1 '07",
    category: "lifestyle",
    price: 115,
    image: "/images/product-1.png",
    label: "Best Seller",
    colors: "2 Colours",
    gender: "men",
    size: ["uk-6", "uk-7", "uk-8", "uk-9", "uk-10"],
    color: "white",
  },
  {
    id: "2",
    name: "Nike Dunk Low Retro",
    category: "lifestyle",
    price: 115,
    image: "/images/product-2.png",
    label: "Best Seller",
    colors: "1 Colour",
    gender: "men",
    size: ["uk-7", "uk-8", "uk-9", "uk-11"],
    color: "black",
  },
  {
    id: "3",
    name: "Nike Air Max 90",
    category: "lifestyle",
    price: 130,
    image: "/images/product-3.png",
    label: "New",
    colors: "3 Colours",
    gender: "women",
    size: ["uk-4", "uk-5", "uk-6", "uk-7"],
    color: "red",
  },
  {
    id: "4",
    name: "Nike Blazer Low '77 Jumbo",
    category: "lifestyle",
    price: 95,
    image: "/images/product-4.png",
    label: "Sustainable Materials",
    colors: "1 Colour",
    gender: "women",
    size: ["uk-5", "uk-6", "uk-7", "uk-8"],
    color: "white",
  },
  {
    id: "5",
    name: "Air Jordan 1 Low",
    category: "basketball",
    price: 115,
    image: "/images/product-5.png",
    label: "",
    colors: "1 Colour",
    gender: "men",
    size: ["uk-8", "uk-9", "uk-10", "uk-11"],
    color: "blue",
  },
  {
    id: "6",
    name: "Nike Metcon 9",
    category: "training",
    price: 150,
    image: "/images/product-6.png",
    label: "Just In",
    colors: "4 Colours",
    gender: "men",
    size: ["uk-7", "uk-8", "uk-9", "uk-10"],
    color: "black",
  },
  {
    id: "7",
    name: "Nike Pegasus 40",
    category: "running",
    price: 130,
    image: "/images/product-7.png",
    label: "",
    colors: "5 Colours",
    gender: "women",
    size: ["uk-4", "uk-5", "uk-6", "uk-7"],
    color: "pink",
  },
  {
    id: "8",
    name: "Nike Air Force 1 Shadow",
    category: "lifestyle",
    price: 130,
    image: "/images/product-8.png",
    label: "Best Seller",
    colors: "2 Colours",
    gender: "women",
    size: ["uk-5", "uk-6", "uk-7"],
    color: "multi-color",
  },
  {
    id: "9",
    name: "Nike Court Vision Low Next Nature",
    category: "lifestyle",
    price: 75,
    image: "/images/product-9.png",
    label: "Sustainable Materials",
    colors: "1 Colour",
    gender: "men",
    size: ["uk-6", "uk-7", "uk-8", "uk-9"],
    color: "white",
  },
  {
    id: "10",
    name: "Nike Air Max SC",
    category: "lifestyle",
    price: 90,
    image: "/images/product-10.png",
    label: "",
    colors: "2 Colours",
    gender: "women",
    size: ["uk-4", "uk-5", "uk-6"],
    color: "white",
  },
];
